/* =========================================================================
   ARTICLES DATA
   -------------------------------------------------------------------------
   Add a new post by adding a new object to this array — nothing else needs
   to change. Newest or oldest first doesn't matter; the page sorts by date
   automatically (most recent first).

   FIELDS
   id      — unique, no spaces (used as the anchor link, e.g. #inflation-outlook)
   title   — post title
   date    — "YYYY-MM-DD" (works fine for posts written before the site existed)
   image   — path to an image, or leave "" to show a plain placeholder block
   teaser  — 1–2 sentence summary shown under the title
   content — array of paragraph strings (each string = one paragraph)
             Start a string with "## " to render it as a bold section
             heading instead of a normal paragraph — e.g. "## The Bottom Line"
   ========================================================================= */

const ARTICLES = [
  {
    id: "grid-hierarchy",
    title: "The Energy Hierarchy: How High-Margin Capital is Colonizing the Grid",
    date: "2026-06-18",
    image: "images/grid_hierarchy_image.png",
    teaser:
      "We like to think of the electrical grid as the ultimate public utility—a shared, democratic piece of infrastructure delivering the same electron to a high-tech facility as it does to a residential home. That version of the grid is dead.",
    content: [
      "Driven by unprecedented, simultaneous spikes in demand, the modern grid is rapidly organizing into a rigid, capital-driven hierarchy. Instead of a shared resource, energy is becoming stratified. The groups with the highest margins are effectively colonizing the most reliable, cleanest power, leaving the rest of society to absorb the volatility of a strained public system.",
      "The new grid hierarchy has five distinct tiers, and the gaps between them is widening by the day:",
      "## Tier 1: High-Margin Biologics & Pharma (The Apex Predators)",
      "When a drug class like GLP-1s generates tens of billions in high-margin revenue, the absolute cost of power is irrelevant—but reliability is everything. A single voltage flicker can ruin a massive batch of highly sensitive bioreactor cultures. Mega-pharma has the capital to build fully redundant, islanded microgrids and secure behind-the-meter generation, ensuring 100% uptime regardless of public grid conditions.",
      "## Tier 2: AI Hyperscalers & Cloud Titans (The Cloud Monopolies)",
      "Right below pharma are the tech giants. Needing massive, continuous baseload power to feed hyperscale data centers while meeting net-zero targets, they are bypassing traditional utility queues entirely. They are ring-fencing the best energy assets for themselves-buying up entire nuclear outputs or locking up utility-scale storage through exclusive Power Purchase Agreements (PPAs).",
      "## Tier 3: Traditional Commerce & Heavy Industry (The Trapped Middle)",
      "Automotive, steel, chemical manufacturing, and standard commercial real estate operate on much tighter margins. They cannot easily absorb a doubling of power costs, yet they are trapped on the public grid. As Tier 1 and 2 outbid them for premium assets, traditional industry is left to bear the brunt of rising transmission charges and volatile wholesale spot markets.",
      "## Tier 4: Mid-to-High Income Residential (The Insulated Consumers)",
      "Affluent homeowners face rising retail rates, but they possess the capital to insulate themselves. By investing in residential solar, home battery systems, and smart efficiency, they can pivot to self-generation during peak pricing or grid instability. They are effectively opting out of the worst parts of the public system.",
      "## Tier 5: Low-Income Residential (The Energy Underclass)",
      "At the absolute base are those with zero capital to invest in efficiency or micro-generation. They are 100% exposed to rising utility rates and spot-market spikes, often paying the highest percentage of their income for the least reliable service.",
      "## The Regulatory Catch-22",
      "This stratification is happening because public utility commissions (PUCs) are utterly unequipped for this concentration of corporate capital.",
      "When a tech or pharma giant offers to fund a massive new substation or pay a heavy premium directly to an Independent Power Producer (IPP), regulators face an impossible choice. Say \"no\" to protect grid equity, and watch those high-paying jobs and tax dollars migrate to another state. Say \"yes,\" and they inadvertently codify a multi-tiered energy society into law.",
      "## The Bottom Line",
      "Energy availability is becoming the ultimate competitive advantage. If capital alone dictates grid resilience, the public grid risks becoming a degraded, volatile asset used only by those who cannot afford to buy their way out of it.",
      "We are moving from an era of energy transition to an era of energy stratification.",
      "The question for leadership is no longer just how much power we can generate—but who gets it when there is not enough for all consumers simultaneously.",
    ],
  },
  {
    id: "the-ai-power-boom-is-racing",
    title: "The AI Power Boom Is Racing Toward a Multi‑Trillion‑Dollar Wall",
    date: "2026-06-30",
    image: "images/the-ai-power-boom-is-racing.png",
    teaser:
      "Tech hyperscalers and utilities have already committed **hundreds of billions** to data centers and **$1.4 trillion** to grid expansion. If AI demand plateaus, those gigawatts don’t disappear - they become a multi‑trillion‑dollar liability split between long Power Purchase Agreements (PPAs) and stranded grid investments. This is where the power goes - and who gets stuck with the bill.",
    content: [
      "## The structural walls facing AI",
      "The AI buildout is colliding with three immediate, real‑world limits:",
      "**The Scaling Limit.** Adding compute and data to large models is producing diminishing returns as high‑quality human data becomes scarce.",
      "**The ROI Disconnect.** Outside a few narrow verticals, most corporate AI pilots are not yet delivering clear financial returns.",
      "**The Workslop Friction.** Indiscriminate automation is polluting corporate data stores with low‑value content, increasing administrative overhead and eroding trust.",
      "These constraints make the demand forecasts that justified massive power commitments fragile.",
      "## Where the excess power goes",
      "If AI demand flattens, secured power won’t vanish - it will be reallocated, with predictable winners and losers:",
      "**Wholesale power glut.** Surplus energy will flow back into local grids, depressing wholesale prices in data‑center hubs.",
      "**Pivot to traditional tech.** Hyperscalers can repurpose high‑density sites for cloud, High Performance Computing (HPC), or advanced manufacturing.",
      "**Crypto and other flexible loads.** Facilities retrofitted from crypto to AI can pivot back to industrial mining or other power‑intensive uses to soak up cheap baseline energy.",
      "## Financial exposure: Big Tech versus regulated utilities",
      "A market correction splits liabilities across two very different ecosystems:",
      "**Big Tech - fixed contractual exposure.** Hyperscalers are locked into **10–20 year PPAs** for baseload power. If AI demand craters, they remain contractually liable - forced to pay, resell at a loss, or absorb termination costs.",
      "**Regulated utilities - stranded assets and political risk.** Utilities are executing **$1.4 trillion** of grid expansion tied to data‑center forecasts. A sudden freeze risks leaving billions in half‑built transmission, substations, and generation capacity stranded — and triggers intense regulatory and political scrutiny over cost recovery.",
      "## How this compares to the past",
      "The 1990s deregulation wave produced a benchmark stranded‑asset event (roughly **$100 billion** then, ~$200 billion inflation‑adjusted). The current AI overhang is **forward‑looking**, embedded in active supply chains, and **orders of magnitude larger** - a combined **$2+ trillion** ecosystem of utility CapEx and Big Tech commitments. Unlike the 1990s, regulators today are less likely to quietly socialize tech‑specific costs onto ratepayers, shifting the initial shock onto private balance sheets and setting up a contentious allocation fight.",
      "## Key takeaways",
      "**Gigawatts already contracted or under construction can’t simply be unplugged.** The physical energy bill remains even if compute demand stalls.",
      "**Hyperscalers face direct PPA pain; utilities face stranded infrastructure and political risk.** Neither side is insulated.",
      "**Markets will reallocate power - but not without winners and losers.** Wholesale buyers, flexible industrial loads, and opportunistic pivots (cloud, HPC, crypto) will benefit; fixed contracts and sunk grid investments will suffer.",
      "## This is a forward‑looking, multi‑trillion‑dollar gamble — not a rerun of the 1990s.",
    ],
  },

  {
    id: "reframing-the-refugee-narrative-an-economic",
    title: "Reframing the Refugee Narrative: An Economic Imperative",
    date: "2026-06-16",
    image: "images/reframing-the-refugee-narrative-an-economic.png",
    teaser:
      "Framing 120 million displaced people in the world solely as a humanitarian crisis isn't working anymore.",
    content: [
      "In today’s political climate, the traditional model of refugee resettlement has flatlined. Look at the numbers:",
      "**1990:** 141,000 refugees rehoused (the high watermark).",
      "**2025:** Fewer than 2,000.",
      "Forcing the old charitable framework won’t change this trajectory. To break the gridlock, we must pivot from a narrative of charity to one of economic utility. We shouldn't just look at refugees as people who need help. We should look at them as part of the talent pool needed to solve our massive, systemic labor deficits.",
      "The Reality of the U.S. Labor Deficit. While our immigration pipelines are choked, the domestic economy is facing a critical workforce shortfall:",
      "**Infrastructure:** The U.S. needs 80,000 new electricians annually. To hit macro infrastructure goals, we face a deficit of 1 million electricians over the next decade.",
      "**Healthcare & Elder Care:** A structural shortfall of 4.6 million caregivers looms by 2032. Additionally, we will be short 86,000 physicians by 2036 and 193,000 nurses annually.",
      "**Tech & Cyber:** 450,000 cybersecurity and critical power engineer roles sit vacant, threatening the build-out of vital AI data centers.",
      "**Industry & Supply Chains:** Up to 2.1 million manufacturing jobs will be unfilled by 2030, alongside an immediate shortage of 80,000 long-haul truckers and 15,000 aviation technicians.",
      "The Fiscal Truth",
      "The primary political barrier to resettlement is the myth of public cost. The data, however, tells a radically different story:",
      "Net Positive Return:",
      "Resettled refugees contribute an average net positive **$2,767 per capita annually** to the government ($12,989 paid in taxes vs. $10,222 consumed in services).",
      "The Economic \"J-Curve\": While integrating carries a net cost for the first 5 years, refugees match native median income by year 10 and out-earn native-born citizens by year 20.",
      "Hyper-Entrepreneurship: Refugees start businesses at a 13% rate, outpacing native-born Americans (9%). Over 190,000 refugee-owned businesses currently generate $6.7 billion in annual revenue.",
      "The Path Forward",
      "The political lens is deeply negative, but we can change the equation by replacing ideology with economics. A thoughtful, needs-based placement strategy can directly match global human capital with our deepest domestic resource gaps. By aligning the drive of the displaced with the critical needs of our workforce, we solve two systemic crises . It’s time to move past the gridlock, address our societal shortfalls, and continue America’s incredible track record of welcoming productive new immigrants—a proud legacy of which I am a first generation example.",
    ],
  },

  {
    id: "what-started-as-a-waistline-fix",
    title: "What started as a waistline fix is officially rewriting the U.S. economy",
    date: "2026-06-09",
    image: "images/what-started-as-a-waistline-fix.jpg",
    teaser:
      "What began as a breakthrough for Type 2 diabetes has become the defining economic disruption of the decade - and we're only in the early innings.",
    content: [
      "## GLP-1: The Macro Shift Hiding in Plain Sight",
      "With 40+ million Americans now on GLP-1 medications and financial barriers crumbling (patent expirations, government pricing caps, oral alternatives), the user base is set to explode. This is no longer a medical trend. It's a structural reset of consumer demand across virtually every sector of the economy, with the implications reaching as far as the national debt.",
      "## Healthcare: A Deflationary Wave",
      "Healthcare spending accounts for nearly 17% of U.S. GDP, driven largely by late-stage treatments for obesity-related chronic disease. Mass GLP-1 adoption is triggering cost deflation across the system - offering a credible path to reining in Medicare expenditures and, by extension, long-term federal debt.",
      "Early data suggest meaningful reductions in cardiovascular events, kidney disease progression, and even Alzheimer's risk. If these hold at scale, we're looking at a generational shift in actuarial models.",
      "## Agribusiness: Composition Over Volume",
      "The disruption here isn't just about how much people eat - it's about what they eat. High-yield crops tied to ultra-processed food (corn syrup, sugar, seed oils) face demand deflation. Meanwhile, lean protein commodities - poultry, whey, cultured dairy, eggs - are surging as users prioritize muscle preservation.",
      "Expect pressure on Big Ag portfolios heavily weighted toward commodity carbohydrates.",
      "## The \"Obesity Industrial Complex\"",
      "Highly profitable pipelines for hip and knee replacements, CPAP machines, dialysis equipment, and bariatric surgery are facing long-term revenue headwinds as systemic population health improves.",
      "Medical device and pharma companies built around treating the consequences of obesity - rather than the cause - will need to diversify or shrink.",
      "## Fitness: From Calorie Burn to Muscle Defense",
      "Gyms are abandoning \"burn calories\" messaging. Why? GLP-1 users face a significant risk of muscle loss if they don't actively counteract it. The fitness industry is pivoting hard toward heavy resistance training, protein optimization, and lean-mass preservation programs.",
      "Expect growth in personal training, strength-focused boutique studios, and wearable tech that tracks body composition - not just weight.",
      "## Retail: The Great Resizing",
      "Brands like Victoria's Secret have seen share price surges as consumer body confidence improves and demand shifts toward core sizing. But the ripple extends to micro-measurements: footwear and fine jewelry are reporting demand spikes as customers discover their shoe and ring sizes have physically shrunk.",
      "Inventory planning across apparel, accessories, and even furniture (think: airplane seats, stadium seating) is being rewritten.",
      "## Alcohol & Beverages: Quiet Disruption",
      "One trend often overlooked: GLP-1 users report dramatically reduced alcohol cravings. Early studies and anecdotal data suggest significant drops in alcohol consumption among this population.",
      "If this holds, expect ripple effects across spirits, beer, wine, hospitality, and even addiction treatment - a multi-hundred-billion-dollar reallocation of consumer spending.",
      "## Transportation: Lighter Passengers, Lower Costs",
      "Wall Street analysts are already factoring passenger weight reductions into airline profitability models. A drop of just 10–12 pounds per passenger saves major carriers millions annually in jet fuel. The math scales to shipping, transit infrastructure, and vehicle design.",
      "## The Bottom Line",
      "We're transitioning from an economy built on sheer volume—more calories, more treatments, more stuff - to one built on targeted efficiency: better products for a consumer who simply requires less.",
      "The businesses that thrive in the next decade will recognize that their target customer is changing - physically, behaviorally, and psychologically - and will adapt fast.",
      "Is your organization building a strategy for a world that consumes less, but buys better?",
      "#GLP1 #Macroeconomics #NationalDebt #BusinessStrategy #FutureOfRetail #HealthcareDisruption",
    ],
  },

  {
    id: "morocco-beyond-the-postcard-the-hidden",
    title: "Morocco Beyond the Postcard: The Hidden Engine Driving North Africa's Transformation",
    date: "2025-12-18",
    image: "images/morocco-beyond-the-postcard-the-hidden.jpg",
    teaser:
      "Like many i suspect, my preconceived notions about Morocco were wildly inaccurate. My recent trip quickly dispelled them, revealing a nation in a dynamic, journey of rapid transformation. Morocco is far more than ancient cities, agriculture and desert landscapes; it is a developing economy driven by a vision for the future.",
    content: [
      "## Morocco: A Nation of Surprises and Momentum",
      "## The Engine of Growth",
      "Morocco demonstrates a clear commitment to development, evident in several key areas:",
      "**• Infrastructure:** High-speed rail, major new road arteries, and ubiquitous utilities underscore a commitment to solid transnational infrastructure. Plus they have avoided ceding control of this development to China or anyone else.",
      "**• Economic Hubs:** Cities like Casablanca are rapidly growing industrial centers, with new construction sharply contrasting with the centuries of history of places like Tangier and Fes.",
      "**• Strong Agriculture:** A robust agricultural sector remains a major foundational component of the economy, crucial for meeting the needs of its growing population.",
      "**• Global Capital:** Investment is powered by substantial Foreign Direct Investment (FDI), largely from Europe, while the global diaspora heavily channels capital into key sectors like real estate and tourism.",
      "**• Global Links:** A substantial global diaspora of 5–6 million reinforces ties to North America, Europe, and the Middle East, facilitating both investment and cultural exchange.",
      "## Sustainability and Challenges",
      "Morocco is actively tackling modern challenges:",
      "**• Renewable Energy & Waste:** While the country is actively investing in renewables, it faces the pervasive and widespread challenge of plastic waste regrettably obvious almost everywhere. One suggestion i would make is to use government policy to encourage, fund and fix using the large number of low income Moroccons who could help across the whole country- \"polishing\" the landscape for a large earning activity namely tourism.",
      "**• Water Security:**With a growing population nearing 50 million, concern over water security is a significant, recognized challenge that will define the future of its agricultural sector.",
      "## Culture and Society",
      "The pervasive hospitality of its people makes for a welcoming experience. Whilst American fast-food influences are evident, the underpinning of traditional Moroccan cuisine remains strong. Furthermore, a government-encouraged focus on education is building the human capital needed for sustained growth.",
      "Notably, the lack of Ottoman influence/invasion is an important element of Morocco's unique development (e.g., wearing the hijab is an individual choice for women). This is coupled with the progressive social foundation reflected by strong property rights for women, which appear to be culturally (if not fully legally) recognized. Morocco has also avoided undue Chinese influence or funding.",
      "## In Summary",
      "Morocco is a complex and highly engaged nation, balancing deep history with swift modernization. Driven by strategic investment, industry, and agriculture, it is a country to watch closely as it executes its ambitious infrastructure and renewable energy strategies.",
      "I want to recognize**Allal Fadili** (#morocco_photographs_tours) for helping me understand and \"see\" his country.",
      "I hope my native Scottish football team survives World Cup contact with them!",
      "#Morocco",
      "#EconomicDevelopment",
      "#EmergingMarkets",
      "#Infrastructure",
      "#RenewableEnergy",
      "https://www.youtube.com/watch?v=kgBhn3Lf958",
    ],
  },

  {
    id: "how-to-save-texas-30-bn",
    title: "How to save Texas $30 Bn",
    date: "2025-02-18",
    image: "images/how-to-save-texas-30-bn.jpg",
    teaser:
      "Roads That Fix Themselves!",
    content: [
      "Roads often get potholes. Especially in geographies that have extremes of heat and cold. These holes make driving uncomfortable and cost a lot of money to fix. But some scientists have found a solution to help.",
      "They discovered that adding used cooking oil (like the oil used to make french fries) to the black stuff used to make roads could help them last longer. Here's how it works:",
      "When tiny cracks start to form in the road, special tiny pockets filled with cooking oil break open. The oil then fills these small cracks before they can get bigger. It's like putting a Band-Aid on a cut before it gets worse!",
      "The scientists tested this in their lab and found that the roads could fix their own tiny cracks in less than an hour! They think roads made this way could last 30% longer than regular roads. Given the aging nature of our infrastructure, this could really help as anybody driving in Houston can attest. The 10-year budget that is approved for Texas transportation is $104 billion.",
      "Fixing road holes costs a lot of money. It's also better for the Earth because it uses old cooking oil that would otherwise be thrown away and cause more pressure on our environment.",
      "A similar development has been used in India, where ground-up plastic and diesel fuel are burnt to create an on-the-spot filler. However, with this solution, there’s a lot of black smoke in the repair.",
      "Perhaps ultimately flying cars will eliminate this need but in the meantime, our aging infrastructure needs all the help it can get.",
      "Just like how your body can heal a small cut by itself, these new roads would be able to heal their own small cracks before they turn into big holes!​",
      "#innovation#environment#leadership",
    ],
  },

  {
    id: "who-is-really-looking-out-for",
    title: "Who is really looking out for low or fixed income electricity users?",
    date: "2024-04-30",
    image: "images/who-is-really-looking-out-for.png",
    teaser:
      "AI and crypto electricity demands are going to pressure low-income energy users. They are also encouraging coal plants to keep operating.",
    content: [
      "The discussion on AI focuses on the speed at which the systems are improving with some discussion around the attendant massive, swift increase in energy usage.",
      "Crypto is also using a lot of the spare capacity in generation outside of the normal patterns of peak usage and surge pricing. Translating this to economics - crypto miners depend on the “spare capacity” that was intended to make the grid more resilient ie they realize the marginal cost of the reserve margin generation. This “spare capacity” was built and paid for by the rate base which did not include either crypto or AI players but did include low-income consumers. Notwithstanding their share of bearing this cost, low-income users have no pre-emptive right to the generation they helped pay for…..",
      "The nature of AI power demand is that it is 24/7 which rules out most forms of standalone renewable generation. At least crypto can be switched on and off. I also still feel that the case for crypto is at best poorly understood and maybe not even real when you consider the cost, ie arbitraging power prices against the value of bitcoin. By the way we haven’t even remotely seen how high AI and crypto will drive power prices, multiples of where the markets are today.",
      "The result of these facts, coupled with inflation and higher interest rates will lead inevitably to two outcomes:",
      "1) The first will be a huge surge in the cost of monthly energy bills.",
      "2) The second is that businesses are able and willing to pay more for the existing electricity than elderly or low-income households who are on fixed incomes.",
      "This will challenge residential users. Many low-income customers are already behind on energy bill payments. What will almost certainly happen is that they will end up not being able to afford or receive electricity. If this happens in the summer in the south or the winter in the north, there will be life-threatening consequences especially for our rapidly aging population with no cash cushion, exacerbated perhaps by being in a large, empty house and locked in place by a “low” interest rate mortgage.",
      "The other aspect of this problem is that the growth in demand is so much faster than any possibility of growth in generation, particularly when you consider the difficulties of actually getting generation or the necessary grid enhancements approved and built. Building a server farm for either AI or crypto is so much faster than the power infrastructure.",
      "It would be reassuring if we heard more significant and thoughtful discussion around this with some commitment to actually creating a resolution that won’t leave people in the dark and cold or hot. Regrettably, none of this will come for free regardless of how much politicians pretend it will be. The size of this problem is staggeringly high- trillions of investment not billions!",
    ],
  },

  {
    id: "is-topline-growth-possible-for-retail",
    title: "Is topline growth possible for retail energy?",
    date: "2024-02-29",
    image: "",
    teaser:
      "I recently posted an article about the risk management challenges retail energy suppliers face. The other side of this question is what can be done to increase the top line, so essential to having a robust, valuable business.",
    content: [
      "There are a range of ways that this can be accomplished however, every single one of them is bounded by constraints or challenges. So far, I do not believe that any player has achieved breakout top-line growth. However, here is a range of approaches that have been tried.",
      "1. **Expand Product Offerings**: Offer additional energy-related products and services such as smart home devices, energy-efficient appliances, or renewable energy options. Diversifying offerings can attract new customers and encourage existing ones to spend more. The challenge here is that none of the additional products or services are without their own suppliers, and the question becomes whether or not the retail Energy company is seen as a credible player. Renewable products do help with certain consumers however, whilst that may boost topline, it typically has not yielded large increases in the bottom line.",
      "2. **Targeted Marketing and Sales**: Use data analytics to identify and target specific customer segments with tailored marketing campaigns. Personalized promotions and offers can increase customer engagement and drive sales. For me, this is actually the most valuable way of improving the value of a business and requires a big data approach. However, it does not increase the top line, but rather the bottom line.",
      "3. **Enhance Customer Experience**: Focus on delivering excellent customer service and support. Investing in user-friendly online platforms, mobile apps, and responsive customer support channels can improve customer satisfaction and retention, leading to increased sales. The challenge in enhancing customer experience is that the customer experience is very simple and most of it is outside of the retail energy suppliers, remit, e.g., the grid.",
      "4. **Partnerships and Alliances**: Form partnerships with other businesses, such as homebuilders, real estate agencies, or technology firms, to cross-promote products and services. Collaborations can expand the customer base and drive mutual growth. although this is a very logical approach, I have tried every single one of these multiple times in the past with little to no success. Part of the problem is that the value created that can be shared is relatively modest compared to what these companies make from their own products therefore they don’t focus on building this part of the business.",
      "5. **Geographical Expansion**: Explore opportunities to enter new markets or expand operations in existing ones. Conduct market research to identify regions with high demand for energy products and tailor marketing strategies accordingly. This again is a logical approach, however, given that the regulation has of anything gone backward, and there are no new territories, in fact, some of the existing territories have become unprofitable, due to burdensome regulation, it is hard to do this in North America.",
      "6. **Value-added Services**: Offer value-added services such as energy audits, efficiency consultations, or personalized energy management plans. These services can help customers optimize their energy usage and save money, leading to increased loyalty and revenue. Again, logical but hard to do. I have not seen anyone bust their top line in a significant way, using this approach. Offering green products is one way the top lane has been bolstered, however typically, without affecting the bottom line in a positive way. The format of deregulation strangles the range of products that can be offered eg reliability.",
      "7. **Customer Referral Programs**: Implement referral programs that incentivize existing customers to refer friends and family. Offering discounts or rewards for successful referrals can stimulate word-of-mouth marketing and attract new customers at a lower acquisition cost. Another traditional approach, which historically has not driven significant growth.",
      "8. **Optimized Pricing Strategies**: Analyze market trends and competitors' pricing to ensure competitive pricing while maintaining profitability. Implement dynamic pricing strategies or bundle pricing options to encourage larger purchases. The retail energy markets are so competitive that this forces a very narrow band of prices, and again topline growth is difficult without losing market share, which, of course, directly reduces the top line.",
      "9. **Invest in Digital Marketing**: Allocate resources to digital marketing channels such as social media, search engine optimization (SEO), and pay-per-click (PPC) advertising. Leveraging digital platforms effectively can increase brand visibility and drive traffic to online sales channels. For me, this is very much now a table stake and therefore, has at best only a modest effect on topline growth.",
      "10. **Customer Loyalty Programs**: Implement loyalty programs that reward repeat purchases and engagement. Offering exclusive perks, discounts, or rewards points can incentivize customers to remain loyal and increase their spending over time. I’m unaware of any successful customer loyalty program in this marketplace.",
      "## ReplyForward",
      "Add reaction",
    ],
  },

  {
    id: "why-the-equivalent-of-the-population",
    title: "Why the equivalent of the population of Spain will die in the next 10 years unless we do something",
    date: "2019-06-13",
    image: "images/why-the-equivalent-of-the-population.jpg",
    teaser:
      "Three billion people cook over open fires – with deadly consequences.”1 Every day women and girls all over the world hazard themselves gathering and then burning biosolids for heating and cooking with attendant deforestation. At the same time they often walk under the glare of flaring natural gas. More than 3% of the world’s natural gas is wastefully flared, 30% of wood-fuel harvesting is unsustainable, and 3+ million people die each year due to smoke inhalation from traditional cookstoves. Surely there is a better integrated solution, through a sustainable business model without the need for subsidy. Primus’s technology provides the profitable and safe answer.",
    content: [
      "1 Nijhuis, M. (2017) Three Billion People Cook Over Open Fires With Deadly Consequences. National Geographic. Retrieved 5 Jul 2018 from: https://www.nationalgeographic.com/photography/proof/2017/07/guatemala-cook-stoves/",
    ],
  },

  {
    id: "some-thoughts-on-the-wrong-and",
    title: "Some thoughts on the wrong and right way to network",
    date: "2017-05-30",
    image: "",
    teaser:
      "Let me first acknowedge I have made all of the mistakes I describe in the first part of this note, the wrong way. The second part is an approach I think is more likely to engender positive interactions.",
    content: [
      "Here is how most \"networking conversations\" start.",
      "First the unspoken part. I know we haven't spoken or corresponded for 2/3/4 years but....\"how are you?\" .....Read I need you now, anyway enough about you. Here is what I was thinking. I lost my job or maybe it is just under threat and I think you might be useful in rectifying that situation.",
      "Please drop everything you are doing and focus on me.",
      "Does any of this sound familiar?",
      "Here is the response most people want to provide.....good luck, call me in another 2/3/4 years and let me know how it turned out for you. But probably, because they are someone you respect and/or you are calling them because of their perceived connections, they will pull out the stops and attempt to help you.",
      "Alternatively here is an approach I have found yields better results.",
      "Cultivate relationships about which you care and don't expect favors to be given but provided by you. Stay in touch because you think the person on the other end is someone you are actually interested in. Someone who perhaps you can help.",
      "Think symbiote not parasite. Try to be useful. Think about the other person and what they might need to be successful. You are a walk-on in their movie, where they are the hero or heroine. They are not a supporting, walk-on in your movie.",
      "Any worthwhile relationship is worth investing in continually and over the longer term. Think wife or husband not a one-night stand. I always find the dating analogy useful as it reduces relationships to terms most folks can relate to....A late night call saying \"how are you?\" does not suggest a relationship you care about.",
      "You want to have a positive relationship balance before you need to withdraw a favor. Most studies on this subject suggest 7 deposits for one withdrawal.",
      "So when you try to withdraw cash prior to depositing you get the normal response, ie in God we trust all others pay cash.",
      "The key is anticipation. Plan ahead. Invest in people you care about or may need well before trying to ask for help.",
      "Single and desperate plays as well in networking as in the dating game. People avoid you like the plague. Play the long game, genuinely think of helping others first.",
      "How can you deploy your network or skills for others? My sons attend Strake Jesuit. The school motto is be \"a man for others\". Words to live by for us all.",
      "So assuming you pass the test of being a person for others, here are some questions you might ask.",
      "What can I do for you, my potential network partner?",
      "Your friends will help regardless. The bigger lift is from those who don't really know you or think about you. Everyone has busy lives. And even if they don't there is always social media to fill it up. Think weak, wide networks not deep, narrow networks.",
      "On the basis of a positive deposit balance ask who are the three people they would recommend you talk to....? Then do your research on those three to see how you can help them and to whom you can usefully introduce them to, all before you ask... Please help me.",
      "Anyway, these are my hard-won lessons, what are yours and how may I help you right now?",
      "Finally, ever thought \"this person\" has nothing to offer me, is boring, is not in a position to help me..? These thoughts are emblematic of our own limitations, not the folks with whom we haven't yet connected or perhaps those with whom we haven't really focused on yet. A failure to find a point of connection is a failure of imagination and thought on our part, not the other person's shortcomings. Work hard at it, unless of course you don't care in which don't be surprised if the other person doesn't care either.",
      "We live in a small, highly connected world. Your brand is generally widely and, perhaps surprisingly, uniformly known regardless of whether you know it or not. Make it something you can be proud of...",
      "P.S. I wish I had known the foregoing before I made all of the above mistakes. The good news is most people are surprisingly forgiving. Good luck.",
    ],
  },

  {
    id: "why-retail-energy-is-so-fundamentally",
    title: "Why retail energy is so fundamentally unstable and in need of disruption.",
    date: "2017-05-21",
    image: "",
    teaser:
      "A substantial number of factors are converging on our industry to fundamentally change the products that our consumers use and how they interact with energy. Where I struggle is how these factors will be synthesized and esp. whether they will benefit current players.",
    content: [
      "I am reminded of the Dickensian novel “A Tale of Two Cities” and the quote from the start of the story- “it was the best of times, it was the worst of times….”",
      "Before we study the retail energy markets I find it instructive to consider other “verticals” that have gone before us into the light….(the nos. and X’s indicate the change in the EV over the last 5 years)",
      "-Retailing shopping- lead by Amazon 5X, aided by advertising from FB 3X",
      "-Hotels – started by VRBO & more completely disrupted by Airbnb ($30 Bn)",
      "-Cars – disrupted on many levels from UBER to the future of autonomous cars – early days so far",
      "-Subset disruption of taxis- UBER ($70 Bn)",
      "-Another subset of electric cars- Tesla ($50 Bn, 10X)",
      "What we do not see are names such as Macy’s (1/2) or Sears (1/7). Take a look at these companies’ share prices or valuations over the last 5 years. They are not performing like unicorns such as UBER nor creating cash mountains like Apple (2X, $250 Bn)….. The best of times for investors in the new companies and the worst of times for the incumbents.",
      "The first category, shopping is defined by disintermediation but with a twist- it uses a community rating as a surrogate for old style brands. I buy products from companies I have never heard of before confident that I will have a good experience. Basically, the brand premium can no longer be extracted from my wallet.",
      "Hotels- creating a clearing market with a great UX/UI that again offers micro brands and again at much-improved value/price. 5 stars replaces the Four Seasons!",
      "Car ownership- has been and will continue to be disrupted mainly because a lot of value is unused. Cars are only used 5 % of the time. Does this sound anything like generation assets? (it does to me). UBER allows me to consume the product I want at the time I want it, with assured quality and a great UI/UX. Gone are the days of a dirty yellow cab with a truculent driver where we would both worry about the settlement process at the end of the trip. Such truculence is now gone, replaced by friendly drivers arriving in clean, air freshened cars offering free water, mints… all at a much lower price with much greater confidence of the pickup window and drop-off. Great for consumers esp. in large cities, the problem of course is stranded assets namely taxi medallions – dropped in value by a factor of 4 in four years.",
      "On the subject of Tesla- NPS 96, and by the way not a regulator in sight! Nor any discussion about whether their factories are large enough to handle demand.",
      "So why did this happen- the incumbents focused on their profit rather than customers’ changing needs powered by new technologies. They didn’t react quickly enough, reassured that all the other frogs looked comfortable in the slowly warming water until it came to the boil in a rush.",
      "So with this recent history to inform us what about our world of retail energy?",
      "Let’s start with demand. Houses are becoming more energy efficient, large white box goods the same. Technology has long been available to help cut out waste – programmable thermostats have been around for thirty years or more. However it took Nest to make it an attractive product that was esthetically pleasing and well marketed that helped cut out waste and it was much easier to use than foregoing products.",
      "But here the story breaks down- now Nest wants to sell me a CO monitor- why, I have no idea. I would rather they improved the UX/UI of their base product. Open the software and let the app developers make it even better. Surely there are standard profiles that could be developed based on lifestyle and family dynamics that would make it easier to save me money. And save a lot. Millennials with a judicious choice of supplier and cutting out wasted cooling/heating could probably cut their bill in half. $500 dollars a year in after-tax earnings? Also regardless of the season I want the thermostat at 74 during the day and 72 on the nights when my family is home, 78 if we are out. It doesn’t change by season so Nest please stop trying to change my settings. The customer-centric view has been lost.",
      "So why don’t the millennials or the customers paying excessive margins in legacy books of business chose- fear, mistrust and uncertainty.",
      "We are presently the classic “me too” product. Our industry is in love with complexity plus it was built on the relationship between generators and regulators.no longer the right approach, we should talk directly to the customers- we have the internet after all.",
      "So our market was built around peak load and rent extraction for having the capacity not the use of generation. Sounds like a market in need of an UBER. What is missing- there was no scarcity price signals to residential consumers, and DR is a really cockeyed way of dealing with this problem. “Let me save you money by making you uncomfortable.” It only really works because of poor market structure.",
      "Returning to generation-the generators have seen the best of times and are now seeing the worst of times…witness one of the largest IPP’s share price drop and the fact they are offering themselves for sale. Is it only me or does anyone else think of the scene from Blazing Saddles where the Sherriff tries to extricate himself from a tough situation by threatening to shoot himself.",
      "To be fair some of their challenge is not self-inflicted. Solar and wind generation have radically altered the generation landscape. And if that wasn’t enough natural gas prices are at sustained low and stable prices. Where did all the volatility go? Well, although the residential customers don’t generally know about the spiky nature of power prices, rest assured C&I customers do. The result- distributed generation that has swiftly penetrated that segment of the market and again depressed volatility. Plus for any stakeholder other than shareholders’ of generation assets, this is a great thing. One green outcome has been less coal and reduced chances of new nuclear. However, in general, our industry’s approach to green is a bit like ordering a big Mac where they ask if you would like extra lettuce. The problem is not treated on a fundamental level. Let’s look at Tesla- the product is faster, priced in a way that produces waitlists, has a mileage range compatible with metropolitan living, never breaks down- that –this is why they have an NPS of 96. It isn’t about tag lines. It isn’t about trying to get customers to treat energy like an all you can eat buffet. It really matches with consumers’ needs and desires. And this is all before batteries really bite……BTW did you see the news about GMP? 2000 power walls…..",
      "So in summary for generators, the brave new world will arise from their ashes. Centrally planned economies do not work witness Venezuela, Cuba, Russia to name but three.",
      "Time and again it is human ingenuity coupled with free market principles that triumphs. In general bureaucrats, politicians and large company executives are spectacularly bad at predicting the future. If you doubt my analysis look at how their share prices are performing. All the while they are slowly but surely losing market share.",
      "Retail energy has basically degenerated into a selling low margin products and then increasing prices and margins over time. The longer you are with a supplier the higher your price is likely to be, how wrong is that? Why is this so, because the investments of yesteryear whether large, out of date IT systems that haven’t been written down yet or substantial amounts of goodwill associated with M&A (carried out to stem eroding customer numbers) result in a need to extract a high economic rent from end users. The consumers realize this on a fundamental, emotional level but don’t know what to do about it. What I find difficult to imagine though is that any consumer will respond to feeling this way by buying more products from those suppliers who have NPS scores that are on average -20. Again don’t take my word for it look at EIA data which shows that on more than 80% of end users in Texas (and this is one of the best markets for consumers) are paying 30% too much on a unit cost basis.",
      "As I said our industry is in love with complexity. Consumers want ease and simplicity, flat bills, low prices, reduction of waste without their active or time-consuming involvement. We are like the old digital watches- every bell and whistle packed into the watch which makes it more complicated to use when all we really wanted was an easy to read, accurate time and date, stopwatch and alarm.",
      "Relating this to Nest or other smart thermostats- find out which days the kids go to school/work, when do you leave the premises, when do you return, when do you go to sleep, when do you wake up and let me import a schedule. Think about what the consumer wants not what you want to sell them. Make it easy- think Amazon Prime- One Click.",
      "While we are on the more connected aspects of the home. To own the home the successful company will need:",
      "To have the ability to create great UX/UI –software for the older folks like me",
      "Deep, consumer electronic hardware expertise",
      "A solid level of trust from the consumer, think of an NPS score north of 50",
      "The requisite size to create economies of scale.",
      "A truly customer-centric culture.",
      "And finally, the necessary financial resources to either build or buy their way into these competencies or capabilities- gigafactories are not cheap ($5Bn) Nest was $3.2 Bn.",
      "Absent satisfying these criteria my recommendation is follow what I believe another large Texas legacy player is about to do by becoming a low-cost provider and shedding non-core assets like renewables.",
      "It is hard not to be at once excited about the new technologies that are improving our world- making us more efficient in the use of scarce commodities….. However, on the other hand, I regret that I find it a step too far that the retail or generator incumbents will lead us into this new world.",
      "Notwithstanding that prognosis I wish them every success in proving me wrong- I don’t believe my powers of prediction are any better than anyone else. But if I am putting money down- and I am – it will be on new entrants or the likes of Apple, Amazon, and Google- and here their share prices strongly support that view.",
      "This is a rare opportunity for me to speak as I see it without having to support any given set of shareholder interests so I can advocate unashamedly for the customer.",
      "I would welcome construct comments.",
    ],
  },
];
